---@class EvolvingTraitsWorldRegistries
ETW_Registry = ETW_Registry or {}

---@class EvolvingTraitsWorldTraitsRegistries
---@field AV_CLUB CharacterTrait
---@field ANEMIC CharacterTrait
---@field ANTI_GUN_ACTIVIST CharacterTrait
---@field AXE_THROWER CharacterTrait
---@field BLOODLUST CharacterTrait
---@field BLISSFUL CharacterTrait
---@field BODYWORK_ENTHUSIAST CharacterTrait
---@field FAST_EATER CharacterTrait
---@field BAD_TEETH CharacterTrait
---@field BUTTERFINGERS CharacterTrait
---@field DEPRESSIVE CharacterTrait
---@field FURNITURE_ASSEMBLER CharacterTrait
---@field GUN_ENTHUSIAST CharacterTrait
---@field GYM_RAT CharacterTrait
---@field HARDY CharacterTrait
---@field HOARDER CharacterTrait
---@field HOME_COOK CharacterTrait
---@field IDEAL_WEIGHT CharacterTrait
---@field LEAD_FOOT CharacterTrait
---@field HOMICHLOPHOBIA CharacterTrait
---@field HOMICHLOPHILE CharacterTrait
---@field BLADE_ENTHUSIAST CharacterTrait
---@field KNIFE_FIGHTER CharacterTrait
---@field LIGHTSTEP CharacterTrait
---@field LOW_PROFILE CharacterTrait
---@field MUNDANE CharacterTrait
---@field NATURAL_EATER CharacterTrait
---@field NOODLE_LEGS CharacterTrait
---@field PLUVIOPHILE CharacterTrait
---@field PLUVIOPHOBIA CharacterTrait
---@field PAIN_TOLERANCE CharacterTrait
---@field PACK_MOUSE CharacterTrait
---@field PACK_MULE CharacterTrait
---@field PET_THERAPY CharacterTrait
---@field POLEARM_FIGHTER CharacterTrait
---@field RESTORATION_EXPERT CharacterTrait
---@field QUICK_REST CharacterTrait
---@field SLOW_EATER CharacterTrait
---@field SUN_SENSITIVITY CharacterTrait
---@field THICK_BLOODED CharacterTrait
---@field WELL_FITTED CharacterTrait
ETW_Registry.traits = {
	AV_CLUB = CharacterTrait.register("ETW:AVClub"),
	ANEMIC = CharacterTrait.register("ETW:Anemic"),
	ANTI_GUN_ACTIVIST = CharacterTrait.register("ETW:AntiGunActivist"),
	AXE_THROWER = CharacterTrait.register("ETW:AxeThrower"),
	BLOODLUST = CharacterTrait.register("ETW:Bloodlust"),
	BLISSFUL = CharacterTrait.register("ETW:Blissful"),
	BODYWORK_ENTHUSIAST = CharacterTrait.register("ETW:BodyWorkEnthusiast"),
	FAST_EATER = CharacterTrait.register("ETW:FastEater"),
	BAD_TEETH = CharacterTrait.register("ETW:BadTeeth"),
	BUTTERFINGERS = CharacterTrait.register("ETW:Butterfingers"),
	DEPRESSIVE = CharacterTrait.register("ETW:Depressive"),
	FURNITURE_ASSEMBLER = CharacterTrait.register("ETW:FurnitureAssembler"),
	GUN_ENTHUSIAST = CharacterTrait.register("ETW:GunEnthusiast"),
	GYM_RAT = CharacterTrait.register("ETW:GymRat"),
	HARDY = CharacterTrait.register("ETW:Hardy"),
	HOARDER = CharacterTrait.register("ETW:Hoarder"),
	HOME_COOK = CharacterTrait.register("ETW:HomeCook"),
	IDEAL_WEIGHT = CharacterTrait.register("ETW:IdealWeight"),
	LEAD_FOOT = CharacterTrait.register("ETW:LeadFoot"),
	HOMICHLOPHOBIA = CharacterTrait.register("ETW:Homichlophobia"),
	HOMICHLOPHILE = CharacterTrait.register("ETW:Homichlophile"),
	BLADE_ENTHUSIAST = CharacterTrait.register("ETW:BladeEnthusiast"),
	KNIFE_FIGHTER = CharacterTrait.register("ETW:KnifeFighter"),
	LIGHTSTEP = CharacterTrait.register("ETW:LightStep"),
	LOW_PROFILE = CharacterTrait.register("ETW:LowProfile"),
	MUNDANE = CharacterTrait.register("ETW:Mundane"),
	NATURAL_EATER = CharacterTrait.register("ETW:NaturalEater"),
	NOODLE_LEGS = CharacterTrait.register("ETW:NoodleLegs"),
	PLUVIOPHILE = CharacterTrait.register("ETW:Pluviophile"),
	PLUVIOPHOBIA = CharacterTrait.register("ETW:Pluviophobia"),
	PAIN_TOLERANCE = CharacterTrait.register("ETW:PainTolerance"),
	PACK_MOUSE = CharacterTrait.register("ETW:PackMouse"),
	PACK_MULE = CharacterTrait.register("ETW:PackMule"),
	PET_THERAPY = CharacterTrait.register("ETW:PetTherapy"),
	POLEARM_FIGHTER = CharacterTrait.register("ETW:PolearmFighter"),
	RESTORATION_EXPERT = CharacterTrait.register("ETW:RestorationExpert"),
	QUICK_REST = CharacterTrait.register("ETW:QuickRest"),
	SLOW_EATER = CharacterTrait.register("ETW:SlowEater"),
	SUN_SENSITIVITY = CharacterTrait.register("ETW:SunSensitivity"),
	THICK_BLOODED = CharacterTrait.register("ETW:ThickBlooded"),
	WELL_FITTED = CharacterTrait.register("ETW:WellFitted"),
	STICK_FIGHTER = CharacterTrait.register("ETW:StickFighter"),
}
