repos:
  - repo: local
    hooks:
      - id: sorted-sandbox-options
        name: Check sandbox option ordering
        entry: python sort_sandbox.py --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      - id: sorted-translation-json
        name: Check translation JSON ordering
        entry: python sort_translation_json.py --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
