repos:
  - repo: local
    hooks:
      - id: sorted-sandbox-options
        name: Check sandbox option ordering
        entry: python sort_sandbox.py --check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]

      # - id: current-translation-stats
      #   name: Check generated translation completion metadata
      #   entry: python update_translation_stats.py --check
      #   language: system
      #   pass_filenames: false
      #   always_run: true
      #   stages: [pre-push]
